"""Markdown + PDF report rendering."""

from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

TEMPLATES = {
    "idor": "idor",
    "bola": "idor",
    "bac": "idor",
    "misconfig": "misconfig",
    "info_disclosure": "info_disclosure",
    "generic": "generic",
}


def build_context(data: dict[str, Any]) -> dict[str, Any]:
    ctx = {
        "title": data.get("title") or "Security Vulnerability Report",
        "researcher": data.get("researcher") or "Security Researcher",
        "email": data.get("email") or "",
        "date": data.get("date") or date.today().isoformat(),
        "asset": data.get("asset") or "N/A",
        "endpoint": data.get("endpoint") or "N/A",
        "vuln_type": data.get("vuln_type") or "Access Control",
        "severity": data.get("severity") or "Medium",
        "cvss_hint": data.get("cvss_hint") or "",
        "cwe": data.get("cwe") or "CWE-639 / CWE-284",
        "summary": data.get("summary") or "",
        "steps": data.get("steps") or [],
        "request": data.get("request") or "",
        "response": data.get("response") or "",
        "impact": data.get("impact") or "",
        "remediation": data.get("remediation")
        or "Enforce object-level authorization on every request. Do not rely on obscurity of IDs.",
        "timeline": data.get("timeline") or [],
        "references": data.get("references")
        or [
            "OWASP Broken Access Control",
            "CWE-639: Authorization Bypass Through User-Controlled Key",
        ],
        "program": data.get("program") or "Responsible Disclosure / VDP",
        "redaction_notes": data.get("redaction_notes") or "",
    }
    if isinstance(ctx["steps"], str):
        ctx["steps"] = [s.strip() for s in ctx["steps"].split("\n") if s.strip()]
    return ctx


def render_markdown(ctx: dict[str, Any], style: str = "hackerone") -> str:
    steps_md = "\n".join(f"{i}. {s}" for i, s in enumerate(ctx["steps"], 1)) or "1. TBD"
    timeline_md = "\n".join(f"- {t}" for t in ctx["timeline"]) or "- Drafted report"
    refs_md = "\n".join(f"- {r}" for r in ctx["references"])
    cvss_line = f"**Severity score hint:** {ctx['cvss_hint']}\n\n" if ctx["cvss_hint"] else ""
    redact = (
        f"\n## Redaction\n\n{ctx['redaction_notes']}\n"
        if ctx["redaction_notes"]
        else ""
    )

    header = {
        "hackerone": f"# {ctx['title']}\n\n**Program:** {ctx['program']}\n\n",
        "certin": (
            f"# Responsible Vulnerability Disclosure Report\n\n"
            f"**To:** CERT-In / Product Security Team\n"
            f"**From:** {ctx['researcher']} <{ctx['email']}>\n"
            f"**Date:** {ctx['date']}\n"
            f"**Subject:** {ctx['title']}\n\n"
        ),
        "vdp": f"# Vulnerability Report — {ctx['title']}\n\n",
    }.get(style, f"# {ctx['title']}\n\n")

    return f"""{header}## Summary

{ctx['summary']}

## Metadata

| Field | Value |
|-------|-------|
| Researcher | {ctx['researcher']} |
| Contact | {ctx['email']} |
| Date | {ctx['date']} |
| Asset | `{ctx['asset']}` |
| Endpoint | `{ctx['endpoint']}` |
| Weakness | {ctx['vuln_type']} |
| CWE | {ctx['cwe']} |
| Severity | **{ctx['severity']}** |

{cvss_line}## Steps to Reproduce

{steps_md}

## Proof of Concept

### Request

```http
{ctx['request'] or 'N/A'}
```

### Response (sanitized)

```http
{ctx['response'] or 'N/A'}
```

## Impact

{ctx['impact']}

## Remediation

{ctx['remediation']}

## Timeline

{timeline_md}

## References

{refs_md}
{redact}
---
*Generated by disclose-cli — for authorized responsible disclosure only.*
"""


def render_pdf(ctx: dict[str, Any], path: Path) -> None:
    styles = getSampleStyleSheet()
    styles.add(
        ParagraphStyle(
            name="BodyJustify",
            parent=styles["BodyText"],
            alignment=TA_JUSTIFY,
            spaceAfter=8,
        )
    )
    styles.add(
        ParagraphStyle(
            name="CodeBlock",
            parent=styles["Code"],
            fontName="Courier",
            fontSize=8,
            leading=10,
            backColor=colors.HexColor("#f4f4f4"),
        )
    )

    doc = SimpleDocTemplate(
        str(path),
        pagesize=A4,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        title=ctx["title"],
        author=ctx["researcher"],
    )
    story: list[Any] = []
    story.append(Paragraph(ctx["title"], styles["Title"]))
    story.append(Spacer(1, 0.15 * inch))
    story.append(
        Paragraph(
            f"Researcher: {ctx['researcher']} | {ctx['email']} | {ctx['date']}",
            styles["Normal"],
        )
    )
    story.append(Spacer(1, 0.2 * inch))

    meta = [
        ["Asset", ctx["asset"]],
        ["Endpoint", ctx["endpoint"]],
        ["Type", ctx["vuln_type"]],
        ["CWE", ctx["cwe"]],
        ["Severity", ctx["severity"]],
        ["Program", ctx["program"]],
    ]
    t = Table(meta, colWidths=[1.5 * inch, 4.5 * inch])
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e8eef7")),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
                ["VALIGN", (0, 0), (-1, -1), "TOP"],
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
            ]
        )
    )
    # fix tuple style
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e8eef7")),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
            ]
        )
    )
    story.append(t)
    story.append(Spacer(1, 0.2 * inch))

    def section(title: str, body: str) -> None:
        story.append(Paragraph(title, styles["Heading2"]))
        for para in (body or "N/A").split("\n"):
            story.append(Paragraph(_esc(para) or " ", styles["BodyJustify"]))

    section("Summary", ctx["summary"])
    story.append(Paragraph("Steps to Reproduce", styles["Heading2"]))
    for i, s in enumerate(ctx["steps"] or ["TBD"], 1):
        story.append(Paragraph(f"{i}. {_esc(s)}", styles["BodyJustify"]))
    section("Impact", ctx["impact"])
    section("Remediation", ctx["remediation"])
    if ctx["request"]:
        story.append(Paragraph("Sample Request (sanitized)", styles["Heading2"]))
        story.append(Paragraph(_esc(ctx["request"])[:2500], styles["CodeBlock"]))
    if ctx["redaction_notes"]:
        section("Redaction notes", ctx["redaction_notes"])

    story.append(Spacer(1, 0.3 * inch))
    story.append(
        Paragraph(
            "<i>Generated by disclose-cli for authorized responsible disclosure only.</i>",
            styles["Normal"],
        )
    )
    doc.build(story)


def _esc(text: str) -> str:
    return (
        (text or "")
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )
